const express = require('express');
const router = express.Router();
const userController = require('../controllers/user-controller');

router.post('/register', userController.registerUser);
router.post('/login', userController.loginUser);
router.get("/pendingDonor", userController.getPendingDonor);
router.get("/pendingReceipient", userController.getPendingReceipient);
router.get("/pendingHospital", userController.getPendingHospital);
router.post("/getDonorDetailsById", userController.getDonorDetailsById);
router.post("/getReceipientDetailsById", userController.getReceipientDetailsById);
router.post("/getHospitalDetailsById", userController.getHospitalDetailsById);
router.post("/login", userController.loginUser);
router.post("/approveDonor", userController.approveDonor);
router.post("/rejectDonor", userController.rejectDonor);
router.post("/approveReceipient", userController.approveReceipient);
router.post("/rejectReceipient", userController.rejectReceipient);
router.post("/approveHospital", userController.approveHospital);
router.post("/rejectHospital", userController.rejectHospital);
router.get("/getUserDetailsById/:id", userController.getUserDetailsById);
router.get("/getHospitalDetailsByid/:id", userController.getHospitalDetailsByid);
router.get("/getDonatedOrgans/:id", userController.getDonatedOrgans);
router.get("/getRequestedOrgans/:id", userController.getRequestedOrgans);
router.put("/updateUserProfile/:id", userController.updateUserProfile);
router.put("/updateHospitalProfile/:id", userController.updateHospitalProfile);
router.post("/submitFeedback", userController.submitFeedback);
router.post("/submitComplaint", userController.submitComplaint);
router.post("/sendRegistrationApprovalEmail", userController.sendRegistrationApprovalEmail);
router.post("/sendRegistrationRejectionEmail", userController.sendRegistrationRejectionEmail);
router.post("/submitDonation", userController.submitDonation);
router.post("/submitRequest", userController.submitRequest);
router.get("/getApprovedHospitals", userController.getApprovedHospitals);
router.get("/getFeedback", userController.getFeedback);
router.get("/getComplaint", userController.getComplaint);
router.post("/fetchMatchedDonor", userController.fetchMatchedDonor);
router.post("/fetchMatchedReceipient", userController.fetchMatchedReceipient);
router.get("/getBloodType/:userid",userController.getBloodType);
router.get("/pendingMatches", userController.getPendingMatches);
router.get("/getDonations/:donorId", userController.getDonations);
router.get("/getRequests/:receipientId", userController.getRequests);
router.put("/updateDonationStatus/:donationId", userController.updateDonationStatus);
router.post("/approveMatch", userController.approveMatch);
module.exports = router;